//
// Created:		04.10.06
// Aurthor:		Iain Gilbert
//

#if defined _testserver_included
	#endinput
#endif

#define _testserver_included
#pragma library testserver

#include "base"

forward testserver_playerconnect(playerid);

public testserver_playerconnect(playerid)
{
//	SendPlayerScrollingText(playerid," Добро пожаловать в Grand Theft Online 0.5.9b3 by FP.");
//	SendPlayerScrollingText(playerid," Этот сервер имеет некоторые изменения, поэтому возможно все.");
//	SendPlayerScrollingText(playerid," Все самые последние изменения в моде GTO будут тестироваться здесь.");
//	SendPlayerScrollingText(playerid," Ошибки, крэши, торможения - это обычное дело для тестового режима.");
}
